### ISSUE TITLE
Error when showing dashboard -  com.tumblr.jumblr.exceptions.JumblrException: Not Found

### ISSUE THREAD

**Issue by Micha-Btz** [oleksiykovtun/Pics-on-Tumblr#2]
hi,

since some days PoT doesn't show the dashboard.

```
10-21 06:45:08.142 E/Error   (17956): Error when showing dashboard
10-21 06:45:08.142 E/Error   (17956): com.tumblr.jumblr.exceptions.JumblrException: Not Found
10-21 06:45:08.142 E/Error   (17956): 	at com.tumblr.jumblr.request.RequestBuilder.clear(RequestBuilder.java:156)
10-21 06:45:08.142 E/Error   (17956): 	at com.tumblr.jumblr.request.RequestBuilder.get(RequestBuilder.java:93)
10-21 06:45:08.142 E/Error   (17956): 	at com.tumblr.jumblr.JumblrClient.blogInfo(JumblrClient.java:138)
10-21 06:45:08.142 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.PictureAlbumLoadTask.doInBackground(PictureAlbumLoadTask.java:53)
10-21 06:45:08.142 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.RepeatableOnErrorAsyncTask.doInBackground(RepeatableOnErrorAsyncTask.java:43)
10-21 06:45:08.142 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.RepeatableOnErrorAsyncTask.doInBackground(RepeatableOnErrorAsyncTask.java:14)
10-21 06:45:08.142 E/Error   (17956): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-21 06:45:08.142 E/Error   (17956): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-21 06:45:08.142 E/Error   (17956): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 06:45:08.142 E/Error   (17956): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 06:45:08.142 E/Error   (17956): 	at java.lang.Thread.run(Thread.java:818)
10-21 06:45:08.340 I/Timeline(2193): Timeline: Activity_windows_visible id: ActivityRecord{e32fd71 u0 com.oleksiykovtun.picsontumblr.android/.view.MainActivity t1250} time:89074118
10-21 06:45:14.573 E/GpsXtraDownloader(2193): No XTRA servers were specified in the GPS configuration
10-21 06:45:15.654 E/Error   (17956): Error when showing dashboard
10-21 06:45:15.654 E/Error   (17956): com.tumblr.jumblr.exceptions.JumblrException: Not Found
10-21 06:45:15.654 E/Error   (17956): 	at com.tumblr.jumblr.request.RequestBuilder.clear(RequestBuilder.java:156)
10-21 06:45:15.654 E/Error   (17956): 	at com.tumblr.jumblr.request.RequestBuilder.get(RequestBuilder.java:93)
10-21 06:45:15.654 E/Error   (17956): 	at com.tumblr.jumblr.JumblrClient.blogInfo(JumblrClient.java:138)
10-21 06:45:15.654 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.PictureAlbumLoadTask.doInBackground(PictureAlbumLoadTask.java:53)
10-21 06:45:15.654 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.RepeatableOnErrorAsyncTask.doInBackground(RepeatableOnErrorAsyncTask.java:43)
10-21 06:45:15.654 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.RepeatableOnErrorAsyncTask.doInBackground(RepeatableOnErrorAsyncTask.java:14)
10-21 06:45:15.654 E/Error   (17956): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-21 06:45:15.654 E/Error   (17956): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-21 06:45:15.654 E/Error   (17956): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 06:45:15.654 E/Error   (17956): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 06:45:15.654 E/Error   (17956): 	at java.lang.Thread.run(Thread.java:818)
10-21 06:45:16.514 E/Error   (17956): Error when showing dashboard
10-21 06:45:16.514 E/Error   (17956): com.tumblr.jumblr.exceptions.JumblrException: Not Found
10-21 06:45:16.514 E/Error   (17956): 	at com.tumblr.jumblr.request.RequestBuilder.clear(RequestBuilder.java:156)
10-21 06:45:16.514 E/Error   (17956): 	at com.tumblr.jumblr.request.RequestBuilder.get(RequestBuilder.java:93)
10-21 06:45:16.514 E/Error   (17956): 	at com.tumblr.jumblr.JumblrClient.blogInfo(JumblrClient.java:138)
10-21 06:45:16.514 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.PictureAlbumLoadTask.doInBackground(PictureAlbumLoadTask.java:53)
10-21 06:45:16.514 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.RepeatableOnErrorAsyncTask.doInBackground(RepeatableOnErrorAsyncTask.java:43)
10-21 06:45:16.514 E/Error   (17956): 	at com.oleksiykovtun.picsontumblr.android.tasks.RepeatableOnErrorAsyncTask.doInBackground(RepeatableOnErrorAsyncTask.java:14)
10-21 06:45:16.514 E/Error   (17956): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-21 06:45:16.514 E/Error   (17956): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-21 06:45:16.514 E/Error   (17956): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 06:45:16.514 E/Error   (17956): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 06:45:16.514 E/Error   (17956): 	at java.lang.Thread.run(Thread.java:818) 
```

Maybe tumblr have changed the api. It is possible to solve?

Another little question is can the app filter always viewed pic's? If you view pictures on the dashboard you may have pictures more then once because more then one blog you followed has reblogged the pics. Would be great if it can be prevented.

TIA Micha

**Comment by oleksiykovtun** [comment]
Dashboard fixed.

Regarding filtering: according to acticle 3e of Tumblr API terms https://www.tumblr.com/docs/en/api_agreement, dashboard is not subject to filtering.
